#include "CliSession.h"

#include "terminal/ShellProcess.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcessEnvironment>
#include <QStandardPaths>

namespace {

const QByteArray kMarkerStart = QByteArrayLiteral("\x1b]133;");

// Reports the end of each command (exit code and directory) and marks the prompt, which is otherwise empty.
const char kBashRc[] = R"(# Generated by QODE for Terminal Only mode.
[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"
__qode_done() { local s=$?; printf '\033]133;D;%s;%s\007' "$s" "$PWD"; return $s; }
__qode_ready() { PS1=$'\033]133;A\007'; PS2=''; PS4='+ '; }
if ((BASH_VERSINFO[0] > 5 || (BASH_VERSINFO[0] == 5 && BASH_VERSINFO[1] >= 1))); then
  PROMPT_COMMAND=(__qode_done "${PROMPT_COMMAND[@]}" __qode_ready)
else
  PROMPT_COMMAND="__qode_done${PROMPT_COMMAND:+;$PROMPT_COMMAND};__qode_ready"
fi
__qode_ready
)";

const char kZshEnv[] = R"(# Generated by QODE for Terminal Only mode.
[[ -r "${QODE_REAL_ZDOTDIR}/.zshenv" ]] && source "${QODE_REAL_ZDOTDIR}/.zshenv"
)";

const char kZshRc[] = R"(# Generated by QODE for Terminal Only mode.
ZDOTDIR="$QODE_REAL_ZDOTDIR"
[[ -r "$ZDOTDIR/.zshrc" ]] && source "$ZDOTDIR/.zshrc"
unsetopt zle PROMPT_CR PROMPT_SP 2>/dev/null
__qode_done() { local s=$?; print -n -- "\e]133;D;$s;$PWD\a" }
__qode_ready() { PROMPT=$'%{\e]133;A\a%}'; RPROMPT=''; PS2='' }
precmd_functions=(__qode_done $precmd_functions __qode_ready)
)";

void writeIfChanged(const QString &path, const char *content)
{
    QFile f(path);
    if (f.open(QIODevice::ReadOnly) && f.readAll() == QByteArray(content))
        return;
    f.close();
    QDir().mkpath(QFileInfo(path).absolutePath());
    if (f.open(QIODevice::WriteOnly | QIODevice::Truncate))
        f.write(content);
}

QString findExecutable(const QStringList &candidates)
{
    for (const QString &c : candidates)
        if (QFileInfo(c).isExecutable())
            return c;
    return {};
}

// Length of the longest suffix of `data` that could be the start of a marker.
int partialMarker(const QByteArray &data)
{
    for (int n = qMin(kMarkerStart.size() - 1, data.size()); n > 0; --n)
        if (data.endsWith(kMarkerStart.left(n)))
            return n;
    return 0;
}

} // namespace

CliSession::CliSession(QObject *parent)
    : QObject(parent)
{
    m_shell = new ShellProcess(this);
    connect(m_shell, &ShellProcess::output, this, &CliSession::onData);
    connect(m_shell, &ShellProcess::finished, this, [this](int code) {
        const bool expected = m_expectedExit;
        m_expectedExit = false;
        setState(State::Stopped);
        if (!expected)
            emit exited(code);
    });
}

CliSession::~CliSession() = default;

QString CliSession::quote(const QString &path)
{
    QString q = path;
    q.replace(QLatin1Char('\''), QStringLiteral("'\\''"));
    return QLatin1Char('\'') + q + QLatin1Char('\'');
}

void CliSession::setState(State s)
{
    if (m_state == s)
        return;
    m_state = s;
    emit stateChanged();
}

// Chooses bash or zsh (the user's shell when it is one of them) and prepares the rc files that report prompts.
bool CliSession::prepareLaunch(QString *program, QStringList *args, QString *error)
{
    const QString userShell = ShellProcess::defaultShell();
    const QString base = QFileInfo(userShell).fileName();
    const QString dir = QStandardPaths::writableLocation(QStandardPaths::GenericCacheLocation) + QStringLiteral("/QODE/cli");

    QString zsh = base == QLatin1String("zsh") ? userShell : QString();
    QString bash = base == QLatin1String("bash") ? userShell : QString();
    if (zsh.isEmpty() && bash.isEmpty()) {
        bash = findExecutable({QStringLiteral("/bin/bash"), QStringLiteral("/usr/bin/bash"), QStringLiteral("/usr/local/bin/bash")});
        if (bash.isEmpty())
            zsh = findExecutable({QStringLiteral("/bin/zsh"), QStringLiteral("/usr/bin/zsh")});
    }
    if (!bash.isEmpty()) {
        writeIfChanged(dir + QStringLiteral("/bashrc"), kBashRc);
        *program = bash;
        *args = {QStringLiteral("--noediting"), QStringLiteral("--rcfile"), dir + QStringLiteral("/bashrc"), QStringLiteral("-i")};
        m_shellName = QStringLiteral("bash");
        return true;
    }
    if (!zsh.isEmpty()) {
        writeIfChanged(dir + QStringLiteral("/zsh/.zshenv"), kZshEnv);
        writeIfChanged(dir + QStringLiteral("/zsh/.zshrc"), kZshRc);
        *program = zsh;
        *args = {QStringLiteral("-i")};
        m_shellName = QStringLiteral("zsh");
        return true;
    }
    if (error)
        *error = tr("Terminal Only mode needs bash or zsh, and neither was found.");
    return false;
}

bool CliSession::start(const QString &directory, QString *error)
{
    if (m_state != State::Stopped)
        return true;
    QString program;
    QStringList args;
    if (!prepareLaunch(&program, &args, error))
        return false;

    QProcessEnvironment env;
    env.insert(QStringLiteral("QODE_TERMINAL_ONLY"), QStringLiteral("1"));
    if (m_shellName == QLatin1String("zsh")) {
        const QString real = qEnvironmentVariable("ZDOTDIR", QDir::homePath());
        env.insert(QStringLiteral("QODE_REAL_ZDOTDIR"), real);
        env.insert(QStringLiteral("ZDOTDIR"),
                   QStandardPaths::writableLocation(QStandardPaths::GenericCacheLocation) + QStringLiteral("/QODE/cli/zsh"));
    }
    m_shell->setLaunch(program, args, env);

    m_carry.clear();
    m_startup.clear();
    m_echoSkip.clear();
    m_queued.clear();
    m_hidden = false;
    m_cwd = directory;
    setState(State::Booting);
    if (!m_shell->start(directory, m_cols, m_rows, error)) {
        setState(State::Stopped);
        return false;
    }
    return true;
}

void CliSession::stop()
{
    if (m_state == State::Stopped)
        return;
    m_expectedExit = true;
    m_shell->terminate(); // the state changes to Stopped once the process is gone
}

void CliSession::resize(int cols, int rows)
{
    m_cols = cols;
    m_rows = rows;
    m_shell->resize(cols, rows);
}

void CliSession::run(const QString &line)
{
    if (m_state == State::Booting) {
        m_queued = line;
        return;
    }
    if (m_state != State::Idle)
        return;
    m_hidden = false;
    m_hiddenOutput.clear();
    m_echoSkip = line.toUtf8() + "\r\n";
    m_clock.start();
    setState(State::Running);
    m_shell->write(line.toUtf8() + '\n');
}

void CliSession::runHidden(const QString &line, std::function<void(int, const QString &)> done)
{
    if (m_state != State::Idle) {
        if (done)
            done(1, tr("The shell is busy."));
        return;
    }
    m_hiddenDone = std::move(done);
    run(line);
    m_hidden = true; // run() clears it
}

void CliSession::write(const QByteArray &bytes)
{
    m_shell->write(bytes);
}

void CliSession::interrupt()
{
    m_shell->write(QByteArrayLiteral("\x03"));
}

void CliSession::onData(const QByteArray &data)
{
    m_carry += data;
    for (;;) {
        const int at = m_carry.indexOf(kMarkerStart);
        if (at < 0) {
            const int keep = partialMarker(m_carry);
            plain(m_carry.left(m_carry.size() - keep));
            m_carry = m_carry.right(keep);
            return;
        }
        plain(m_carry.left(at));
        const int end = m_carry.indexOf('\x07', at);
        if (end < 0) {
            m_carry = m_carry.mid(at);
            return;
        }
        marker(m_carry.mid(at + kMarkerStart.size(), end - at - kMarkerStart.size()));
        m_carry = m_carry.mid(end + 1);
    }
}

void CliSession::plain(const QByteArray &bytes)
{
    QByteArray data = bytes;
    if (data.isEmpty())
        return;
    switch (m_state) {
    case State::Booting:
        if (m_startup.size() < 65536)
            m_startup += data;
        break;
    case State::Running:
        // Drop the tty's echo of the line we submitted (its first bytes after submitting).
        if (!m_echoSkip.isEmpty()) {
            const int n = qMin(m_echoSkip.size(), data.size());
            if (data.left(n) == m_echoSkip.left(n)) {
                m_echoSkip.remove(0, n);
                data.remove(0, n);
            } else {
                m_echoSkip.clear();
            }
        }
        if (data.isEmpty())
            break;
        if (m_hidden)
            m_hiddenOutput += data;
        else
            emit output(data);
        break;
    case State::Idle:
        emit backgroundOutput(data);
        break;
    default:
        break;
    }
}

void CliSession::marker(const QByteArray &body)
{
    if (body.startsWith('D')) {
        const QList<QByteArray> parts = body.split(';');
        const int code = parts.value(1).toInt();
        if (parts.size() > 2) {
            const QString dir = QString::fromUtf8(body.mid(body.indexOf(';', 2) + 1));
            if (!dir.isEmpty() && dir != m_cwd) {
                m_cwd = dir;
                emit cwdChanged(dir);
            }
        }
        if (m_state == State::Running) {
            const qint64 ms = m_clock.elapsed();
            m_echoSkip.clear();
            const bool hidden = m_hidden;
            m_hidden = false;
            setState(State::Idle);
            if (hidden) {
                auto done = std::move(m_hiddenDone);
                m_hiddenDone = nullptr;
                const QString out = QString::fromUtf8(m_hiddenOutput);
                m_hiddenOutput.clear();
                if (done)
                    done(code, out);
            } else {
                m_lastExit = code;
                emit commandFinished(code, ms);
            }
        }
    } else if (body.startsWith('A')) {
        if (m_state == State::Booting) {
            const QString text = QString::fromUtf8(m_startup);
            m_startup.clear();
            setState(State::Idle);
            if (!text.trimmed().isEmpty())
                emit startupOutput(text);
            if (!m_queued.isEmpty()) {
                const QString line = m_queued;
                m_queued.clear();
                run(line);
            }
        }
    }
}
